# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwtutil < Formula
  desc "handy little jwt debugging utility to encode/decode tokens"
  homepage "https://github.com/goware/jwtutil"
  version "0.5.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goware/jwtutil/releases/download/v0.5.7/jwtutil.darwin-amd64"
      sha256 "3d7582ac7023d6d875c9ad961a9814aa5015ad4b89d8b16b05408686f71b8b33"

      def install
        bin.install "jwtutil.darwin-amd64" => "jwtutil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goware/jwtutil/releases/download/v0.5.7/jwtutil.darwin-arm64"
      sha256 "9968269a636697da1cd0f9947635a80a6714a2b8c548538f14ea20ba90600238"

      def install
        bin.install "jwtutil.darwin-arm64" => "jwtutil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goware/jwtutil/releases/download/v0.5.7/jwtutil.linux-arm64"
      sha256 "414ef08b8bb2a642a9e562828a070c6c0b702bbfb47ac080c2b178423c9da00b"

      def install
        bin.install "jwtutil.linux-arm64" => "jwtutil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goware/jwtutil/releases/download/v0.5.7/jwtutil.linux-amd64"
      sha256 "7597eba8bdfbbe6d5145ccbcd963f5c36ddade563f8c7a66addb8446f24f0a41"

      def install
        bin.install "jwtutil.linux-amd64" => "jwtutil"
      end
    end
  end
end
